### ISSUE TITLE
LocalIO Update

### ISSUE THREAD

**Issue by olzhabay** [DICL/VeloxDFS#142]
In [localio](https://github.com/DICL/VeloxDFS/blob/c67a521bb7a8301b9b7616d77cde1901abc5a818/src/blocknode/local_io.hh#L14) function update should pass value variable by reference, so it will not double copy.

**Comment by vicentebolea** [comment]
Thanks for point out @olzhabay Gotcha! Please write PR, we will merge quickly :)

**Comment by olzhabay** [comment]
#143

**Comment by vicentebolea** [comment]
Following up at the PR #143. Closing issue
